CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE progress (
id INTEGER PRIMARY KEY AUTOINCREMENT,
orgName TEXT NOT NULL,
type TEXT NOT NULL,
date DATE NOT NULL,
hours NUMERIC NOT NULL,
points NUMERIC NOT NULL, person_id INT NOT NULL);
CREATE TABLE users (
id INTEGER PRIMARY KEY AUTOINCREMENT,
username TEXT NOT NULL,
password TEXT NOT NULL,
points NUMERIC NOT NULL DEFAULT 0,
hours NUMERIC NOT NULL DEFAULT 0,
pic TEXT DEFAULT "default.png");
